GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY '1234' WITH GRANT OPTION;
FLUSH PRIVILEGES;


-- jmedu 데이터베이스 생성
CREATE DATABASE IF NOT EXISTS jmedu;

SHOW WARNINGS;

USE jmedu;

CREATE TABLE smartFarm (
  idx INT AUTO_INCREMENT PRIMARY KEY,
  run BOOLEAN NOT NULL,
  sys_fan BOOLEAN NOT NULL,
  pump BOOLEAN NOT NULL,
  humidity_sensor INT NOT NULL,
  soil_sensor1 INT NOT NULL,
  soil_sensor2 INT NOT NULL,
  temp_sensor INT NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL
);

CREATE TABLE member (
  idx INT AUTO_INCREMENT PRIMARY KEY,
  id VARCHAR(255) NOT NULL,
  pw VARCHAR(255) NOT NULL,
  phone VARCHAR(20) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  deleted_at DATETIME DEFAULT NULL
);